### ISSUE TITLE
$stmt_index missing in function freeStmt

### ISSUE THREAD

**Issue by pepeverde9** [hexblot/mssql-compat#3]
Hello
I have to move some legacy code to a new ubuntu system.
Your wrapper is quite convenient to be used, but I found that my system issues the following:
Notice: Undefined variable: stmt_index in /usr/local/share/php/mssql-compat/mssql_compat.php on line 318

This is true, there is no $stmt_index in this function:
```
    public function freeStmt($stmt) {
      $stmt = &$this->getStmtObj($stmt, TRUE);
      unset($this->stmt_pool[$stmt_index]);
      return TRUE;
    }

```
I guess it shoud be:
```
    public function freeStmt($stmt) {
      $stmt_index = &$this->getStmtObj($stmt, TRUE);
      unset($this->stmt_pool[$stmt_index]);
      return TRUE;
    }

```

**Comment by hexblot** [comment]
Good catch, committed.
